#!/bin/bash
source build/envsetup.sh
repopick -p 301152 301157 # DT
repopick -p 291006 # QTI telephony
repopick 291060 # ditto
repopick -p 297547 # devicesettings
repopick 295023
repopick 295969 # FOD fixes
repopick -t android11-gsi
repopick -t eleven-bt-sbc-hd-dualchannel
repopick 301219
repopick 300535 # USB denial fix
